name: Test Workflow

on:
  push:
    branches:
      - main   # change if your default branch is different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3000113@ds.study.iitm.ac.in
        run: echo "Hello, world!"
